<wsdl:definitions
     name="DeleteHeaderTbl"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/WingPOS/ExpeditorReturnOrders/DeleteHeaderTbl"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/WingPOS/ExpeditorReturnOrders/DeleteHeaderTbl"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/DeleteHeaderTbl"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="DeleteHeaderTbl_plt" >
    <plt:role name="DeleteHeaderTbl_role" >
      <plt:portType name="tns:DeleteHeaderTbl_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="DeleteHeaderTbl_plt" >
    <plt:role name="DeleteHeaderTbl_role" >
      <plt:portType name="tns:DeleteHeaderTbl_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DeleteHeaderTbl" schemaLocation="../Schemas/DeleteHeaderTbl.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DeleteHeaderTbl" schemaLocation="../Schemas/DeleteHeaderTbl.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="DeleteHeaderTblInput_msg">
        <wsdl:part name="DeleteHeaderTblInput_msg" element="db:DeleteHeaderTblInput"/>
    </wsdl:message>
    <wsdl:portType name="DeleteHeaderTbl_ptt">
        <wsdl:operation name="DeleteHeaderTbl">
            <wsdl:input message="tns:DeleteHeaderTblInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
