<wsdl:definitions
     name="DeleteDetailTbl"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/WingPOS/ExpeditorReturnOrders/DeleteDetailTbl"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/WingPOS/ExpeditorReturnOrders/DeleteDetailTbl"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/DeleteDetailTbl"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="DeleteDetailTbl_plt" >
    <plt:role name="DeleteDetailTbl_role" >
      <plt:portType name="tns:DeleteDetailTbl_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="DeleteDetailTbl_plt" >
    <plt:role name="DeleteDetailTbl_role" >
      <plt:portType name="tns:DeleteDetailTbl_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DeleteDetailTbl" schemaLocation="../Schemas/DeleteDetailTbl.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DeleteDetailTbl" schemaLocation="../Schemas/DeleteDetailTbl.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="DeleteDetailTblInput_msg">
        <wsdl:part name="DeleteDetailTblInput_msg" element="db:DeleteDetailTblInput"/>
    </wsdl:message>
    <wsdl:portType name="DeleteDetailTbl_ptt">
        <wsdl:operation name="DeleteDetailTbl">
            <wsdl:input message="tns:DeleteDetailTblInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
