<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:ns0="http://schema.ibd.specialized.com/pos/wing/return"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertReturnHeader"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://xmlns.oracle.com/WingPOS/ExpeditorReturnOrders/ReturnOrders"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/WingPOS/ExpeditorReturnOrders/InsertReturnHeader">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/ReturnOrders.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ReturnOrderResponse"
                                       namespace="http://schema.ibd.specialized.com/pos/wing/return"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/InsertReturnHeader.wsdl"/>
        <oracle-xsl-mapper:rootElement name="SbcCnPoOutboundHeaderCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertReturnHeader"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI FEB 10 10:17:19 PST 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:variable name="dossierNum"/>
  <xsl:template match="/">
    <tns:SbcCnPoOutboundHeaderCollection>
      <xsl:for-each select="/ns0:ReturnOrderResponse/ns0:Rows/ns0:ReturnOrders">
        <tns:SbcCnPoOutboundHeader>
          <tns:dossierNumber>
            <xsl:value-of select="$dossierNum"/>
          </tns:dossierNumber>
          <tns:shipmentHeaderId>
            <xsl:value-of select="ns0:Id"/>
          </tns:shipmentHeaderId>
          <tns:shipmentNum>
            <xsl:value-of select="ns0:OriginalOrderNo"/>
          </tns:shipmentNum>
          <tns:containerNum>
            <xsl:value-of select='"B2CRETURN"'/>
          </tns:containerNum>
          <tns:lastUpdateDate>
            <xsl:value-of select="xp20:current-dateTime ( )"/>
          </tns:lastUpdateDate>
          <tns:creationDate>
            <xsl:value-of select="xp20:current-dateTime ( )"/>
          </tns:creationDate>
        </tns:SbcCnPoOutboundHeader>
      </xsl:for-each>
    </tns:SbcCnPoOutboundHeaderCollection>
  </xsl:template>
</xsl:stylesheet>
