<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:tns="http://schema.ibd.specialized.com/pos/wing/return/file"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:ns0="http://schema.ibd.specialized.com/pos/wing/return"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns1="http://ibd.specialized.com/WingPOS/ExpeditorReturnOrders"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 ns1 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns2="http://xmlns.oracle.com/WingPOS/ExpeditorReturnOrders/ReturnOrders"
                xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/ftp/WingPOS/ExpeditorReturnOrders/WriteReturnFile"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/ReturnOrders.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ReturnOrderResponse"
                                       namespace="http://schema.ibd.specialized.com/pos/wing/return"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/ExpeditorReturnOrderProcess.wsdl"/>
        <oracle-xsl-mapper:rootElement name="flowID"
                                       namespace="http://ibd.specialized.com/WingPOS/ExpeditorReturnOrders"/>
        <oracle-xsl-mapper:param name="batch_number"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/WriteReturnFile.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ReturnOrderFile"
                                       namespace="http://schema.ibd.specialized.com/pos/wing/return/file"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON JUN 05 06:50:58 PDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="batch_number"/>
  <xsl:template match="/">
    <tns:ReturnOrderFile>
      <xsl:for-each select="/ns0:ReturnOrderResponse/ns0:Rows/ns0:ReturnOrderProducts">
        <tns:Orders>
          <tns:ShipmentNumber>
            <xsl:value-of select="concat(B2CRETURN, $batch_number/ns1:flowID)"/>
          </tns:ShipmentNumber>
          <tns:LineNumber>
            <xsl:value-of select='"1"'/>
          </tns:LineNumber>
          <tns:ItemNumber>
            <xsl:value-of select="ns0:ProductCode"/>
          </tns:ItemNumber>
          <tns:ExpectedReceiptDate>
            <xsl:value-of select="ns0:CreationDate"/>
          </tns:ExpectedReceiptDate>
          <tns:QuantityExpected>
            <xsl:value-of select="ns0:Num"/>
          </tns:QuantityExpected>
          <xsl:variable name="ordid" select="ns0:OMSOnlineOrderId"/>
          <xsl:for-each select="/ns0:ReturnOrderResponse/ns0:Rows/ns0:ReturnOrders[ns0:Id = $ordid]">
            <tns:PurchaseOrder>
              <xsl:value-of select="/ns0:ReturnOrderResponse/ns0:Rows/ns0:ReturnOrders[ns0:Id = $ordid]/ns0:Id"/>
            </tns:PurchaseOrder>
            <tns:PurchaseOrderLine>
              <xsl:value-of select='"1"'/>
            </tns:PurchaseOrderLine>
            <tns:SupplierName>
              <xsl:value-of select="/ns0:ReturnOrderResponse/ns0:Rows/ns0:ReturnOrders[ns0:Id = $ordid]/ns0:ReceivName"/>
            </tns:SupplierName>
          </xsl:for-each>
          <tns:ContainerNumber>
            <xsl:value-of select='"B2CRETURN"'/>
          </tns:ContainerNumber>
        </tns:Orders>
      </xsl:for-each>
    </tns:ReturnOrderFile>
  </xsl:template>
</xsl:stylesheet>
