<wsdl:definitions
     name="WriteReturnFile"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/WingPOS/ExpeditorReturnOrders/WriteReturnFile"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ftp/WingPOS/ExpeditorReturnOrders/WriteReturnFile"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:imp1="http://schema.ibd.specialized.com/pos/wing/return/file"
    >
  <plt:partnerLinkType name="Write_plt" >
    <plt:role name="Write_role" >
      <plt:portType name="tns:Write_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/WingPOS/ExpeditorReturnOrders/WriteReturnFile"
              xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://schema.ibd.specialized.com/pos/wing/return/file" schemaLocation="../Schemas/nxsd_return_order_file.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="Write_msg">
        <wsdl:part name="body" element="imp1:ReturnOrderFile"/>
    </wsdl:message>
    <wsdl:portType name="Write_ptt">
        <wsdl:operation name="Write">
            <wsdl:input message="tns:Write_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
