<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:tns="http://TargetNamespace.com/ReturnReceipt_Operation1_request"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://ibd.specialized.com/WingPOS/ExpeditorReturnReceipt"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://schema.ibd.specialized.com/pos/wing/return"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/ftp/WingPOS/ExpeditorReturnReceipt/writeJson"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/UpdateReturnReceiptProcess.wsdl"/>
        <oracle-xsl-mapper:rootElement name="process"
                                       namespace="http://ibd.specialized.com/WingPOS/ExpeditorReturnReceipt"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/writeJson.wsdl"/>
        <oracle-xsl-mapper:rootElement name="AddParams"
                                       namespace="http://TargetNamespace.com/ReturnReceipt_Operation1_request"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [SAT FEB 25 10:15:20 PST 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:AddParams>
      <tns:ReceivName>
        <xsl:value-of select="/ns0:process/ns0:ReceivName"/>
      </tns:ReceivName>
      <tns:OriginalOrderNo>
        <xsl:value-of select="/ns0:process/ns0:OriginalOrderNo"/>
      </tns:OriginalOrderNo>
      <tns:ReceivMobile>
        <xsl:value-of select="/ns0:process/ns0:ReceivMobile"/>
      </tns:ReceivMobile>
      <tns:OMSStorageInProduct>
        <tns:Num>
          <xsl:value-of select="/ns0:process/ns0:OMSStorageInProduct/ns0:Num"/>
        </tns:Num>
        <tns:ROWSTATUS>
          <xsl:value-of select="/ns0:process/ns0:OMSStorageInProduct/ns0:ROWSTATUS"/>
        </tns:ROWSTATUS>
        <tns:Sku>
          <xsl:value-of select="/ns0:process/ns0:OMSStorageInProduct/ns0:Sku"/>
        </tns:Sku>
        <tns:Title>
          <xsl:value-of select="/ns0:process/ns0:OMSStorageInProduct/ns0:Title"/>
        </tns:Title>
      </tns:OMSStorageInProduct>
      <tns:IESStoreId>
        <xsl:value-of select="/ns0:process/ns0:IESStoreId"/>
      </tns:IESStoreId>
      <tns:ROWSTATUS>
        <xsl:value-of select="/ns0:process/ns0:ROWSTATUS"/>
      </tns:ROWSTATUS>
      <tns:OMSRefundOrderId>
        <xsl:value-of select="/ns0:process/ns0:OMSRefundOrderId"/>
      </tns:OMSRefundOrderId>
    </tns:AddParams>
  </xsl:template>
</xsl:stylesheet>
