<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="UpdateReturnOrders"
     targetNamespace="http://xmlns.oracle.com/WingPOS/ExpeditorReturnReceipt/UpdateReturnOrders"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:client="http://xmlns.oracle.com/WingPOS/ExpeditorReturnReceipt/UpdateReturnOrders"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:ns1="http://schema.ibd.specialized.com/pos/wing/return"
    >
    <plnk:partnerLinkType name="UpdateReturnOrders">
        <plnk:role name="UpdateReturnOrdersProvider" portType="client:UpdateReturnOrders"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/WingPOS/ExpeditorReturnReceipt/UpdateReturnOrders"
                 schemaLocation="../Schemas/UpdateReturnOrders.xsd"/>
        </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://schema.ibd.specialized.com/pos/wing/return" schemaLocation="../Schemas/WingAddParams.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="UpdateReturnOrdersRequestMessage">
        <wsdl:part name="payload" element="client:process"/>
    </wsdl:message>
    <wsdl:message name="UpdateReturnOrdersResponseMessage">
        <wsdl:part name="payload" element="client:processResponse"/>
    </wsdl:message>
    <wsdl:portType name="UpdateReturnOrders">
        <wsdl:operation name="process">
            <wsdl:input message="client:UpdateReturnOrdersRequestMessage"/>
            <wsdl:output message="client:UpdateReturnOrdersResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
