<wsdl:definitions
     name="RollbackTBL"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/WingPOS/ExpeditorShipping/RollbackTBL"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/WingPOS/ExpeditorShipping/RollbackTBL"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/RollbackTBL"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="RollbackTBL_plt" >
    <plt:role name="RollbackTBL_role" >
      <plt:portType name="tns:RollbackTBL_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/RollbackTBL" schemaLocation="../Schemas/RollbackTBL.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="RollbackTBLInput_msg">
        <wsdl:part name="RollbackTBLInput_msg" element="db:RollbackTBLInput"/>
    </wsdl:message>
    <wsdl:portType name="RollbackTBL_ptt">
        <wsdl:operation name="RollbackTBL">
            <wsdl:input message="tns:RollbackTBLInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
