<wsdl:definitions
     name="UpdateTBLNEW"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/WingPOS/ExpeditorShipping/UpdateTBLNEW"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/WingPOS/ExpeditorShipping/UpdateTBLNEW"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateTBLNEW"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="UpdateTBLNEW_plt" >
    <plt:role name="UpdateTBLNEW_role" >
      <plt:portType name="tns:UpdateTBLNEW_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateTBLNEW" schemaLocation="../Schemas/UpdateTBLNEW_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="SbcExpeditorShipconfirmCollection_msg">
        <wsdl:part name="SbcExpeditorShipconfirmCollection" element="top:SbcExpeditorShipconfirmCollection"/>
    </wsdl:message>
    <wsdl:portType name="UpdateTBLNEW_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:SbcExpeditorShipconfirmCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
