<wsdl:definitions
     name="UpdateStagingTable"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/WingPOS/ExpeditorShipping/UpdateStagingTable"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/WingPOS/ExpeditorShipping/UpdateStagingTable"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/UpdateStagingTable"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="UpdateStagingTable_plt" >
    <plt:role name="UpdateStagingTable_role" >
      <plt:portType name="tns:UpdateStagingTable_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="UpdateStagingTable_plt" >
    <plt:role name="UpdateStagingTable_role" >
      <plt:portType name="tns:UpdateStagingTable_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="UpdateStagingTable_plt" >
    <plt:role name="UpdateStagingTable_role" >
      <plt:portType name="tns:UpdateStagingTable_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/UpdateStagingTable" schemaLocation="../Schemas/UpdateStagingTable.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/UpdateStagingTable" schemaLocation="../Schemas/UpdateStagingTable.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/UpdateStagingTable" schemaLocation="../Schemas/UpdateStagingTable.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="UpdateStagingTableInput_msg">
        <wsdl:part name="UpdateStagingTableInput_msg" element="db:UpdateStagingTableInput"/>
    </wsdl:message>
    <wsdl:portType name="UpdateStagingTable_ptt">
        <wsdl:operation name="UpdateStagingTable">
            <wsdl:input message="tns:UpdateStagingTableInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
