<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://schema.ibd.specialized.com/pos/wing/shipment"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/TrackingNumberPolling"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/WingPOS/ExpeditorShipping/TrackingNumberPolling"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns2="http://xmlns.oracle.com/WingPOS/ExpeditorShipping/UpdateShipment">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/TrackingNumberPolling.wsdl"/>
        <oracle-xsl-mapper:rootElement name="SbcExpeditorShipconfirmCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/TrackingNumberPolling"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/UpdateShipment.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ShipmentUpdateRequest"
                                       namespace="http://schema.ibd.specialized.com/pos/wing/shipment"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON APR 24 15:09:13 PDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <xsl:for-each select="/ns0:SbcExpeditorShipconfirmCollection/ns0:SbcExpeditorShipconfirm">
      <tns:ShipmentUpdateRequest>
        <tns:APP_KEY>
          <xsl:value-of select="dvm:lookupValue('oramds:/apps/DVMs/WingUpdateShipment.dvm','Property','app_key','Value','TBD')"/>
        </tns:APP_KEY>
        <tns:METHOD>
          <xsl:value-of select="dvm:lookupValue('oramds:/apps/DVMs/WingUpdateShipment.dvm','Property','method','Value','TBD')"/>
        </tns:METHOD>
        <tns:ORDERID>
          <xsl:value-of select="substring-after (ns0:waybill, 'T' )"/>
        </tns:ORDERID>
        <tns:LOGISTICSNO>
          <xsl:value-of select="ns0:trackingNumber"/>
        </tns:LOGISTICSNO>
        <tns:TIMESTAMP>
          <xsl:value-of select="xp20:current-date()"/>
        </tns:TIMESTAMP>
        <tns:V>
          <xsl:value-of select="dvm:lookupValue('oramds:/apps/DVMs/WingUpdateShipment.dvm','Property','version','Value','TBD')"/>
        </tns:V>
        <tns:SIGN>
          <xsl:value-of select='"1"'/>
        </tns:SIGN>
        <tns:TYPE>
          <xsl:value-of select="dvm:lookupValue('oramds:/apps/DVMs/WingUpdateShipment.dvm','Property','type','Value','TBD')"/>
        </tns:TYPE>
        <!--
        <tns:LOGISTICSID>
          <xsl:value-of select='"STO"'/>
        </tns:LOGISTICSID>
        -->
      </tns:ShipmentUpdateRequest>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
