<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns1="http://ibd.specialized.com/WingPOS/ExpeditorImport/ExpeditorImportProcess"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://schema.ibd.specialized.com/pos/wing/order"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertOrdersNew"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns1 ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:ns4="http://www.example.org" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns2="http://xmlns.oracle.com/WingPOS/ExpeditorImport/Order"
                xmlns:ns3="http://schemas.oracle.com/bpel/extension" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns5="http://xmlns.oracle.com/pcbpel/adapter/db/WingPOS/ExpeditorImport/InsertOrdersNew"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/Order.wsdl"/>
        <oracle-xsl-mapper:rootElement name="OrderResponse"
                                       namespace="http://schema.ibd.specialized.com/pos/wing/order"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/ExpeditorImportProcess.wsdl"/>
        <oracle-xsl-mapper:rootElement name="flowID"
                                       namespace="http://ibd.specialized.com/WingPOS/ExpeditorImport/ExpeditorImportProcess"/>
        <oracle-xsl-mapper:param name="batch_number"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/InsertOrdersNew.wsdl"/>
        <oracle-xsl-mapper:rootElement name="SbcExpeditorSentOlCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertOrdersNew"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED MAY 10 21:31:52 PDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="batch_number"/>
  <xsl:template match="/">
    <tns:SbcExpeditorSentOlCollection>
      <xsl:for-each select="/ns0:OrderResponse/ns0:Rows/ns0:OrderProducts">
        <xsl:for-each select="/ns0:OrderResponse/ns0:Rows/ns0:Orders">
          <tns:SbcExpeditorSentOl>
            <tns:deliveryId>
              <xsl:value-of select="ns0:Id"/>
            </tns:deliveryId>
            <tns:deliveryDetailId>
              <xsl:value-of select="/ns0:OrderResponse/ns0:Rows/ns0:OrderProducts/ns0:Id"/>
            </tns:deliveryDetailId>
            <tns:sourceHeaderId>
              <xsl:value-of select="ns0:Id"/>
            </tns:sourceHeaderId>
            <tns:sourceLineId>
              <xsl:value-of select="/ns0:OrderResponse/ns0:Rows/ns0:OrderProducts/ns0:Id"/>
            </tns:sourceLineId>
            <tns:status>
              <xsl:value-of select='"SENT"'/>
            </tns:status>
            <tns:creationDate>
              <xsl:value-of select="xp20:current-date ( )"/>
            </tns:creationDate>
            <tns:createdBy>
              <xsl:value-of select="$batch_number/ns1:flowID"/>
            </tns:createdBy>
            <tns:lastUpdatedBy>
              <xsl:value-of select="$batch_number/ns1:flowID"/>
            </tns:lastUpdatedBy>
            <tns:lastUpdateDate>
              <xsl:value-of select="xp20:current-date ( )"/>
            </tns:lastUpdateDate>
            <tns:batchNumber>
              <xsl:value-of select="$batch_number/ns1:flowID"/>
            </tns:batchNumber>
            <tns:waybill>
              <xsl:value-of select="ns0:Id"/>
            </tns:waybill>
            <tns:segment1>
              <xsl:value-of select="/ns0:OrderResponse/ns0:Rows/ns0:OrderProducts/ns0:ProductCode"/>
            </tns:segment1>
            <tns:industryStandardCod>
              <xsl:value-of select="/ns0:OrderResponse/ns0:Rows/ns0:OrderProducts/ns0:Sku"/>
            </tns:industryStandardCod>
            <tns:quantity>
              <xsl:value-of select="/ns0:OrderResponse/ns0:Rows/ns0:OrderProducts/ns0:Num"/>
            </tns:quantity>
          </tns:SbcExpeditorSentOl>
        </xsl:for-each>
      </xsl:for-each>
    </tns:SbcExpeditorSentOlCollection>
  </xsl:template>
</xsl:stylesheet>
