<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns1="http://ibd.specialized.com/WingPOS/ExpeditorImport/ExpeditorImportProcess"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://schema.ibd.specialized.com/pos/wing/order"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertOrdersNew"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns1 ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:ns4="http://www.example.org" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns2="http://xmlns.oracle.com/WingPOS/ExpeditorImport/Order"
                xmlns:ns3="http://schemas.oracle.com/bpel/extension" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns5="http://xmlns.oracle.com/pcbpel/adapter/db/WingPOS/ExpeditorImport/InsertOrdersNew"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/Order.wsdl"/>
        <oracle-xsl-mapper:rootElement name="OrderResponse"
                                       namespace="http://schema.ibd.specialized.com/pos/wing/order"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/ExpeditorImportProcess.wsdl"/>
        <oracle-xsl-mapper:rootElement name="flowID"
                                       namespace="http://ibd.specialized.com/WingPOS/ExpeditorImport/ExpeditorImportProcess"/>
        <oracle-xsl-mapper:param name="batch_number"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/InsertOrdersNew.wsdl"/>
        <oracle-xsl-mapper:rootElement name="SbcExpeditorSentOlCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertOrdersNew"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED MAY 10 22:12:16 PDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="batch_number"/>
  <xsl:template match="/">
    <tns:SbcExpeditorSentOlCollection>
      <xsl:for-each select="/ns0:OrderResponse/ns0:Rows/ns0:OrderProducts">
        <tns:SbcExpeditorSentOl>
          <tns:deliveryId>
            <xsl:value-of select="ns0:OMSOnlineOrderId"/>
          </tns:deliveryId>
          <tns:deliveryDetailId>
            <xsl:value-of select="ns0:Id"/>
          </tns:deliveryDetailId>
          <tns:sourceHeaderId>
            <xsl:value-of select="ns0:OMSOnlineOrderId"/>
          </tns:sourceHeaderId>
          <tns:sourceLineId>
            <xsl:value-of select="ns0:Id"/>
          </tns:sourceLineId>
          <tns:status>
            <xsl:value-of select='"SENT"'/>
          </tns:status>
          <tns:creationDate>
            <xsl:value-of select="xp20:current-date ( )"/>
          </tns:creationDate>
          <tns:createdBy>
            <xsl:value-of select="$batch_number/ns1:flowID"/>
          </tns:createdBy>
          <tns:lastUpdatedBy>
            <xsl:value-of select="$batch_number/ns1:flowID"/>
          </tns:lastUpdatedBy>
          <tns:lastUpdateDate>
            <xsl:value-of select="xp20:current-date ( )"/>
          </tns:lastUpdateDate>
          <tns:batchNumber>
            <xsl:value-of select="$batch_number/ns1:flowID"/>
          </tns:batchNumber>
          <xsl:variable name="ordid" select="ns0:OMSOnlineOrderId"/>
          <tns:countryCode>
            <xsl:value-of select='"CN"'/>
          </tns:countryCode>
          <tns:shipToOrgId>
            <xsl:value-of select="concat (ns0:OMSOnlineOrderId, ns0:OMSOnlineOrderId )"/>
          </tns:shipToOrgId>
          <tns:waybill>
            <xsl:value-of select="concat ('T', ns0:OMSOnlineOrderId )"/>
          </tns:waybill>
          <tns:segment1>
            <xsl:value-of select="ns0:ProductCode"/>
          </tns:segment1>
          <tns:descriptionJa>
            <xsl:value-of select="ns0:Title"/>
          </tns:descriptionJa>
          <tns:industryStandardCod>
            <xsl:value-of select="ns0:Sku"/>
          </tns:industryStandardCod>
          <tns:quantity>
            <xsl:value-of select="ns0:Num"/>
          </tns:quantity>
          <xsl:variable name="my_var">
            <xsl:value-of select="position()"/>
          </xsl:variable>
          <xsl:for-each select="/ns0:OrderResponse/ns0:Rows/ns0:Orders[ns0:Id = $ordid]">
            <xsl:variable name="ordcnt" select="position()"/>
            <tns:customerName>
              <xsl:value-of select="/ns0:OrderResponse/ns0:Rows/ns0:Orders[ns0:Id = $ordid]/ns0:ReceivName"/>
            </tns:customerName>
            <tns:address1>
              <xsl:value-of select="/ns0:OrderResponse/ns0:Rows/ns0:Orders[ns0:Id = $ordid]/ns0:ReceivAddress"/>
            </tns:address1>
            <tns:address2>
              <xsl:value-of select="/ns0:OrderResponse/ns0:Rows/ns0:Orders[ns0:Id = $ordid]/ns0:ShortAddress"/>
            </tns:address2>
            <tns:shipToPhone>
              <xsl:value-of select="/ns0:OrderResponse/ns0:Rows/ns0:Orders[ns0:Id = $ordid]/ns0:ReceivMobile"/>
            </tns:shipToPhone>
            <tns:postalCode>
              <xsl:value-of select="/ns0:OrderResponse/ns0:Rows/ns0:Orders[ns0:Id = $ordid]/ns0:ReceivZip"/>
            </tns:postalCode>
            <tns:city>
              <xsl:value-of select="/ns0:OrderResponse/ns0:Rows/ns0:Orders[ns0:Id = $ordid]/ns0:ReceivCityName"/>
            </tns:city>
            <tns:state>
              <xsl:value-of select="/ns0:OrderResponse/ns0:Rows/ns0:Orders[ns0:Id = $ordid]/ns0:ReceivAreaName"/>
            </tns:state>
            <tns:customerPhone>
              <xsl:value-of select="/ns0:OrderResponse/ns0:Rows/ns0:Orders[ns0:Id = $ordid]/ns0:ReceivMobile"/>
            </tns:customerPhone>
            <tns:freightAmount>
              <xsl:value-of select="/ns0:OrderResponse/ns0:Rows/ns0:Orders[ns0:Id = $ordid]/ns0:ShipAmount"/>
            </tns:freightAmount>
            <tns:orderTotalAmount>
              <xsl:value-of select="/ns0:OrderResponse/ns0:Rows/ns0:Orders[ns0:Id = $ordid]/ns0:OrderAmount"/>
            </tns:orderTotalAmount>
            <tns:shipMethod>
              <xsl:value-of select="/ns0:OrderResponse/ns0:Rows/ns0:Orders[ns0:Id = $ordid]/ns0:ShipperCode"/>
            </tns:shipMethod>
            <tns:shipToName>
              <xsl:value-of select="/ns0:OrderResponse/ns0:Rows/ns0:Orders[ns0:Id = $ordid]/ns0:ShopTitle"/>
            </tns:shipToName>
            <tns:orderNumber>
              <xsl:value-of select="/ns0:OrderResponse/ns0:Rows/ns0:Orders[ns0:Id = $ordid]/ns0:Id"/>
            </tns:orderNumber>
            <tns:orderLineNumber>
              <xsl:value-of select="$ordcnt"/>
            </tns:orderLineNumber>
          </xsl:for-each>
          <tns:country>
            <xsl:value-of select='"CN"'/>
          </tns:country>
          <tns:custPoNumber>
            <xsl:value-of select="ns0:OMSOnlineOrderId"/>
          </tns:custPoNumber>
          <tns:descriptionUs>
            <xsl:value-of select="ns0:Title"/>
          </tns:descriptionUs>
          <tns:orderClass>
            <xsl:value-of select='"TMALL"'/>
          </tns:orderClass>
          <tns:listPrice>
            <xsl:value-of select="ns0:StandardPrice"/>
          </tns:listPrice>
          <tns:sellingPrice>
            <xsl:value-of select="ns0:Price"/>
          </tns:sellingPrice>
          <tns:lineTotalAmount>
            <xsl:value-of select="ns0:RealAmount"/>
          </tns:lineTotalAmount>
          <tns:format>
            <xsl:value-of select='"WING"'/>
          </tns:format>
          <tns:headerNote>
            <xsl:value-of select='"Phone #: 400-820-6380      Email: CustomerService.CN@specialized.com"'/>
          </tns:headerNote>
        </tns:SbcExpeditorSentOl>
      </xsl:for-each>
    </tns:SbcExpeditorSentOlCollection>
  </xsl:template>
</xsl:stylesheet>
