<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertOrders"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://schema.ibd.specialized.com/pos/wing/order"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns1="http://xmlns.oracle.com/WingPOS/ExpeditorImport/Order"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/WingPOS/ExpeditorImport/InsertOrders">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/Order.wsdl"/>
        <oracle-xsl-mapper:rootElement name="OrderResponse"
                                       namespace="http://schema.ibd.specialized.com/pos/wing/order"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/InsertOrders.wsdl"/>
        <oracle-xsl-mapper:rootElement name="SbcExpeditorStgTblCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertOrders"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED JAN 11 15:50:26 PST 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:SbcExpeditorStgTblCollection>
      <xsl:for-each select="/ns0:OrderResponse/ns0:Rows/ns0:Orders[ns0:OrderStatus=3]">
<xsl:variable name="v1">
<xsl:value-of select="/ns0:Id/text()"/></xsl:variable>
        <xsl:for-each select="/ns0:OrderResponse/ns0:Rows/ns0:OrderProducts[ns0:OMSOnlineOrderId=v1/text()]">
        
        <tns:SbcExpeditorStgTbl>
          <tns:orderNumber>
            <xsl:value-of select="ns0:Id"/>
          </tns:orderNumber>
          <tns:orderDate>
            <xsl:value-of select="ns0:OrderDate"/>
          </tns:orderDate>
          <tns:orderStatus>
            <xsl:value-of select="ns0:OrderStatus"/>
          </tns:orderStatus>
          <tns:item>
              <xsl:value-of select="ns0:Sku"/>
            </tns:item>
          </tns:SbcExpeditorStgTbl>
        
        </xsl:for-each>        
      </xsl:for-each>
    </tns:SbcExpeditorStgTblCollection>
  </xsl:template>
</xsl:stylesheet>
