<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertOrders"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:tns="http://schema.ibd.specialized.com/pos/wing/order/file"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/WingPOS/ExpeditorImport/InsertOrders"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/ftp/WingPOS/ExpeditorImport/WriteFile">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/InsertOrders.wsdl"/>
        <oracle-xsl-mapper:rootElement name="SbcExpeditorStgTblCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertOrders"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/WriteFile.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Orders" namespace="http://schema.ibd.specialized.com/pos/wing/order/file"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU JAN 05 14:05:33 PST 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:variable name="file_name"/>
  <xsl:template match="/">
    <tns:Orders>
      <xsl:for-each select="/ns0:SbcExpeditorStgTblCollection/ns0:SbcExpeditorStgTbl">
        <tns:Order>
          <tns:WAYBILL>
            <xsl:value-of select='concat ("T", ns0:orderNumber )'/>
          </tns:WAYBILL>
          <tns:LINE_NUMBER>
            <xsl:value-of select="ns0:orderLineNumber"/>
          </tns:LINE_NUMBER>
          <tns:INDUSTRY_STANDARD_COD>
            <xsl:value-of select="ns0:upcCode"/>
          </tns:INDUSTRY_STANDARD_COD>
          <tns:SEGMENT1>
            <xsl:value-of select="ns0:productCode"/>
          </tns:SEGMENT1>
          <tns:DESCRIPTION_JA>
            <xsl:value-of select="ns0:itemDescription"/>
          </tns:DESCRIPTION_JA>
          <tns:QUANTITY>
            <xsl:value-of select="ns0:orderLineQuantity"/>
          </tns:QUANTITY>
          <tns:CUSTOMER_NUMBER>
            <xsl:value-of select="concat (999999, ns0:orderShopId )"/>
          </tns:CUSTOMER_NUMBER>
          <tns:SHIP_TO_ORG_ID>
            <xsl:value-of select="concat (999999, ns0:orderShopId )"/>
          </tns:SHIP_TO_ORG_ID>
          <tns:CUSTOMER_NAME>
            <xsl:value-of select="ns0:customerName"/>
          </tns:CUSTOMER_NAME>
          <tns:SHIP_TO_ADDRESS1>
            <xsl:value-of select="ns0:customerAddress"/>
          </tns:SHIP_TO_ADDRESS1>
          <!--
          <tns:SHIP_TO_ADDRESS2>
            <xsl:value-of select="&#x9;"/>
          </tns:SHIP_TO_ADDRESS2>
          -->
          <tns:SHIP_TO_CITY>
            <xsl:value-of select="ns0:customerCityName"/>
          </tns:SHIP_TO_CITY>
          <tns:SHIP_TO_STATE>
            <xsl:value-of select="ns0:customerProvinceName"/>
          </tns:SHIP_TO_STATE>
          <tns:SHIP_TO_POSTAL_CODE>
            <xsl:value-of select="ns0:customerZip"/>
          </tns:SHIP_TO_POSTAL_CODE>
          <tns:SHIP_TO_COUNTRY>
            <xsl:value-of select='"CN"'/>
          </tns:SHIP_TO_COUNTRY>
          <!-- Adding TAB space
          <tns:SHIP_TO_CONTACT>
            <xsl:value-of select="" separator="&#x9;"/>
          </tns:SHIP_TO_CONTACT>
          -->
          <tns:SHIP_TO_PHONE>
            <xsl:value-of select="ns0:customerPhone"/>
          </tns:SHIP_TO_PHONE>
          <tns:SELLING_PRICE>
            <xsl:value-of select="format-number(ns0:standardPrice,'#.####')"/>
          </tns:SELLING_PRICE>
          <tns:LIST_PRICE>
            <xsl:value-of select="format-number(ns0:price,'#.####')"/>
          </tns:LIST_PRICE>
          <tns:LINE_TOTAL_AMOUNT>
            <xsl:value-of select="format-number(ns0:lineTotalAmount,'#.####')"/>
          </tns:LINE_TOTAL_AMOUNT>
          <tns:ORDER_TOTAL_AMOUNT>
            <xsl:value-of select="format-number(ns0:orderTotalAmount,'#.####')"/>
          </tns:ORDER_TOTAL_AMOUNT>
          <tns:CUST_PO_NUMBER>
            <xsl:value-of select="ns0:orderNumber"/>
          </tns:CUST_PO_NUMBER>
          <tns:REQUEST_DATE>
            <xsl:value-of select='xp20:format-dateTime(xp20:current-date(),"[Y0001]/[M01]/[D01]")'/>
          </tns:REQUEST_DATE>
          <tns:PROMISED_DATE>
            <xsl:value-of select='xp20:format-dateTime(xp20:current-date(),"[Y0001]/[M01]/[D01]")'/>
          </tns:PROMISED_DATE>
          <tns:HEADER_NOTE>
            <xsl:value-of select='"Phone #: 400-820-6380      Email: CustomerService.CN@specialized.com"'/>
          </tns:HEADER_NOTE>
          <tns:ORDER_NUMBER>
            <xsl:value-of select="ns0:orderNumber"/>
          </tns:ORDER_NUMBER>
          <tns:ORDER_LINE_NUMBER>
            <xsl:value-of select="ns0:orderLineNumber"/>
          </tns:ORDER_LINE_NUMBER>
          <tns:ITEM_TYPE>
            <xsl:value-of select="ns0:SkuSpec"/>
          </tns:ITEM_TYPE>
          <tns:SHIP_METHOD>
            <xsl:value-of select="dvm:lookupValue('oramds:/apps/DVMs/WingShipMethod.dvm', 'Property',ns0:shipperCode, 'Value', 'TBD')"/>
          </tns:SHIP_METHOD>
          <tns:ORDER_CLASS>
            <xsl:value-of select='"TMALL"'/>
          </tns:ORDER_CLASS>
          <tns:CUSTOMR_PHONE>
            <xsl:value-of select="ns0:customerMobile"/>
          </tns:CUSTOMR_PHONE>
          <tns:FREIGHT_AMOUNT>
            <xsl:value-of select='concat(format-number(ns0:shipAmount,"#.####")," ")'/>
          </tns:FREIGHT_AMOUNT>
        </tns:Order>
      </xsl:for-each>
    </tns:Orders>
  </xsl:template>
</xsl:stylesheet>
